package com.loqoai.ProductFinder.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * The Product class represents the product schema in the MySQL database.
 * This entity maps to the "products" table in the database.
 */
@Entity
@Table(name = "products")
@Data
@NoArgsConstructor
public class Product {

    /**
     * The unique identifier for the product.
     * This is the primary key and is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the product.
     * This field cannot be null.
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * The category to which the product belongs.
     * This field cannot be null.
     */
    @Column(name = "category", nullable = false)
    private String category;

    /**
     * The price of the product.
     * This field cannot be null.
     */
    @Column(name = "price", nullable = false)
    private double price;

    /**
     * Indicates whether the product is in stock.
     * This field cannot be null.
     */
    @Column(name = "in_stock", nullable = false)
    private boolean inStock;

    /**
     * The rating of the product.
     * This field cannot be null.
     */
    @Column(name = "rating", nullable = false)
    private double rating;

    /**
     * The date and time when the product was created.
     * This field cannot be null and is stored with timestamp precision.
     */
    @Column(name = "created_at", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    /**
     * Constructor to create a new Product instance.
     *
     * @param name       The name of the product.
     * @param category   The category of the product.
     * @param price      The price of the product.
     * @param inStock    Indicates whether the product is in stock.
     * @param rating     The rating of the product.
     * @param createdAt  The date and time when the product was created.
     */
    public Product(String name, String category, double price, boolean inStock, double rating, Date createdAt) {
        this.name = name;
        this.category = category;
        this.price = price;
        this.inStock = inStock;
        this.rating = rating;
        this.createdAt = createdAt;
    }
}
